### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by pickfire** [PhilTaken/rpi-image-flake#1]
I stumbled across this repository but I am wondering how to build the image with nix flake.

**Comment by PhilTaken** [comment]
Ah right, its not that intuitive when you're new to flakes :)

When building with flakes you just select the output to build basically.

I added the images output section for exactly that.
It boils down to

`nix build .#images.rpi4` 

if you have it cloned locally or

`nix build "github:PhilTaken/rpi-image-flake#images.rpi4"`

anywhere else.

I just noticed the issue linked under the rpi4-new output has since been fixed.
I'll just update the flake and the lockfile, test the build and push it 

I think I'll also add a little readme incase others run across this :thinking: 
Thanks for pointing this out :+1:

**Comment by PhilTaken** [comment]
Updated the lockfile and tested that it builds with the newest nixpkgs.

I don't have a spare raspberry pi laying around that I could test it on but in theory it should boot.
If you have any more questions about flakes, nixos on the raspberry pi or nixos in general feel free to reach out to me :)
